### ISSUE TITLE
Compliation warnings with Elixir 1.11

### ISSUE THREAD

**Issue by Rio517** [puid/Elixir#6]
```
==> crypto_rand
Compiling 1 file (.ex)
warning: :crypto.strong_rand_bytes/1 defined in application :crypto is used by the current application but the current application does not directly depend on :crypto. To fix this, you must do one of:

  1. If :crypto is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :crypto is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :crypto, you may optionally skip this warning by adding [xref: [exclude: :crypto]] to your "def project" in mix.exs

Found at 6 locations:
  lib/crypto_rand.ex:60: CryptoRand.random/2
  lib/crypto_rand.ex:112: CryptoRand.shuffle/2
  lib/crypto_rand.ex:164: CryptoRand.take_random/3
  lib/crypto_rand.ex:218: CryptoRand.uniform/2
  lib/crypto_rand.ex:244: CryptoRand.uniform_list/3
  lib/crypto_rand.ex:346: CryptoRand.uniform_bytes/3
```

I will submit a PR in a moment.

**Comment by Maxximiliann** [comment]
Hi!

This very same error just cropped up for me. How do I resolve it?

**Comment by Rio517** [comment]
You can use my fork - see the linked PR.

**Comment by Maxximiliann** [comment]
> You can use my fork - see the linked PR.

Cool! How should I add this as in my mix.exs deps?

**Comment by Maxximiliann** [comment]
After deleting the mix.lock file and all deps, I updated the mix file with [{:puid, "~> 1.0"}](https://github.com/Rio517/Elixir#installation) and then ran `mix deps.get` only to have the same error message crop up again . . . 

What am I missing?

**Comment by Rio517** [comment]
You need this in your mix file.
`{:puid, "~> 1.1", git: "git@github.com:Rio517/Elixir.git"},`

**Comment by Maxximiliann** [comment]
> You need this in your mix file.
> `{:puid, "~> 1.1", git: "git@github.com:Rio517/Elixir.git"},`

```
$ mix deps.get
* Getting puid (git@github.com:Rio517/Elixir.git)
ssh_askpass: exec(/usr/bin/ssh-askpass): No such file or directory
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
** (Protocol.UndefinedError) protocol String.Chars not implemented for %IO.Stream{device: :standard_io, line_or_bytes: :line, raw: false} of type IO.Stream (a struct)
    (elixir 1.11.2) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir 1.11.2) lib/string/chars.ex:22: String.Chars.to_string/1
    (mix 1.11.2) lib/mix/scm/git.ex:274: Mix.SCM.Git.git!/2
    (mix 1.11.2) lib/mix/scm/git.ex:124: Mix.SCM.Git.checkout/2
    (elixir 1.11.2) lib/file.ex:1552: File.cd!/2
    (mix 1.11.2) lib/mix/dep/fetcher.ex:64: Mix.Dep.Fetcher.do_fetch/3
    (mix 1.11.2) lib/mix/dep/converger.ex:190: Mix.Dep.Converger.all/9
    (mix 1.11.2) lib/mix/dep/converger.ex:201: Mix.Dep.Converger.all/9
```

**Comment by Maxximiliann** [comment]
> You need this in your mix file.
> `{:puid, "~> 1.1", git: "git@github.com:Rio517/Elixir.git"},`

```
$ git clone git@github.com:Rio517/Elixir.git
Cloning into 'Elixir'...
Warning: Permanently added the RSA host key for IP address '140.82.112.3' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by Rio517** [comment]
My fork is in a public repo. That seems to indicate an error with your local configuration. Can you clone any other public repo?  If you need further debugging help, please reach me on twitter @rio517 and I'll do what I can. I want to keep this issue thread clean to make it as easy as possible for the maintainer to focus on the underlying issue.

**Comment by Maxximiliann** [comment]
Changing `{:puid, "~> 1.1", git: "git@github.com:Rio517/Elixir.git"} ` to  `{:puid, "~> 1.1", github: "Rio517/Elixir"}` and then adding   
```
def application do
    [
      extra_applications: [:crypto_rand]
    ]
  end
```
to the `Puid.Mixfile` resolved the problem. Thanks for all your help :)

**Comment by dingosky** [comment]
Thx Mario. I'm finally emerging from a Covid fog cast upon the company I work for. Anyway, I merged your pull request and believe all is well with this issue.
